const slugifyProductName = (name: string): string =>
  name
    .toString()
    .toLowerCase()
    .trim()
    .replace(/[\s_]+/g, "-")
    .replace(/[^\w-]+/g, "")
    .replace(/--+/g, "-");

export const normalizeSku = (sku: string): string => sku.trim().toUpperCase();

/** Matches seed format: FTM-CHICKENCURRYCUT-1000G */
export const generateVariantSku = (productName: string, weightGrams: number): string => {
  const slug = slugifyProductName(productName);
  const code = slug.replace(/-/g, "").toUpperCase() || "PRODUCT";
  const weight = Math.max(1, Math.round(weightGrams));
  return normalizeSku(`FTM-${code}-${weight}G`);
};

export const isAutoGeneratedSku = (
  sku: string,
  productName: string,
  weightGrams: number,
): boolean => {
  const trimmed = sku.trim();
  if (!trimmed) return true;
  return normalizeSku(trimmed) === generateVariantSku(productName, weightGrams);
};

const COMMON_VARIANT_WEIGHTS = [250, 500, 1000, 2000, 100, 3000, 5000] as const;

/** Pick the next unused weight (grams) so auto SKUs stay unique per variant. */
export const suggestNextVariantSize = (usedSizes: number[]): number => {
  const used = new Set(usedSizes.map((size) => Math.round(size)));
  for (const weight of COMMON_VARIANT_WEIGHTS) {
    if (!used.has(weight)) return weight;
  }
  let candidate = Math.max(0, ...used) + 250;
  while (used.has(candidate)) candidate += 250;
  return candidate;
};
